# Generated by Django 6.0 on 2026-03-24 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='部门表')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门表')),
                ('age', models.CharField(max_length=100, verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('asset', models.DateTimeField(max_length=100, verbose_name='收入')),
                ('creat_time', models.DateTimeField(verbose_name='入职时间')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_one.department')),
            ],
        ),
    ]
