# Generated by Django 6.0 on 2026-03-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='asset',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收入'),
        ),
    ]
