# Generated by Django 6.0 on 2026-03-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0002_rename_creat_time_userinfo_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_one.department', verbose_name='部门'),
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('status', models.IntegerField(choices=[(1, '已使用'), (2, '未使用')], verbose_name='使用状态')),
                ('times', models.CharField(max_length=100, verbose_name='创建时间')),
                ('price', models.CharField(max_length=1000, verbose_name='价格')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_one.userinfo', verbose_name='使用者')),
            ],
        ),
    ]
