# Generated by Django 6.0 on 2026-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0003_alter_userinfo_depart_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='asset',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='收入'),
            preserve_default=False,
        ),
    ]
