# Generated by Django 5.2.12 on 2026-03-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0004_remove_userinfo_asset_userinfo_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('role', models.IntegerField(choices=[(1, '员工'), (2, '管理员'), (3, '领导')], default=1, verbose_name='身份')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
        ),
    ]
