# Generated by Django 5.2.12 on 2026-03-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0005_sysuser'),
    ]

    operations = [
    ]
