# Generated by Django 6.0 on 2026-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0006_auto_20260331_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('role', models.IntegerField(choices=[(1, '员工'), (2, '领导'), (3, '管理员')], verbose_name='角色')),
            ],
        ),
        migrations.DeleteModel(
            name='SysUser',
        ),
    ]
