# Generated by Django 5.2.12 on 2026-04-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0007_adminrole_delete_sysuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='任务标题')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='完成状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_one.adminrole', verbose_name='负责人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='project_one.adminrole', verbose_name='创建人')),
            ],
        ),
    ]
