# Generated by Django 5.2.12 on 2026-04-07 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0008_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_one.adminrole', verbose_name='接收员工'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='状态'),
        ),
    ]
