# Generated by Django 6.0 on 2026-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0009_alter_task_assignee_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=32, verbose_name='订单号')),
                ('source', models.CharField(max_length=32, verbose_name='来源')),
                ('title', models.CharField(max_length=32, verbose_name='客户姓名')),
                ('times', models.DateField(verbose_name='成交日期')),
                ('price', models.CharField(max_length=32, verbose_name='成交金额')),
                ('name', models.CharField(max_length=32, verbose_name='销售人员')),
                ('image', models.CharField(max_length=128, verbose_name='详情')),
            ],
        ),
    ]
