# Generated by Django 5.2.12 on 2026-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0010_perform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perform',
            name='image',
            field=models.ImageField(upload_to='perform/', verbose_name='业绩图片'),
        ),
    ]
